package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"autoapi/graph/model"
	"context"
)

// StoreConfig is the resolver for the storeConfig field.
func (r *mutationResolver) StoreConfig(ctx context.Context, config model.ServerConfigInput) (*model.ServerConfig, error) {
	return r.ServerConfigService.StoreConfig(ctx, config)
}

// DeleteServerConfig is the resolver for the deleteServerConfig field.
func (r *mutationResolver) DeleteServerConfig(ctx context.Context, id string) (bool, error) {
	return r.ServerConfigService.DeleteServerConfig(ctx, id)
}

// DeleteAllServerConfigs is the resolver for the deleteAllServerConfigs field.
func (r *mutationResolver) DeleteAllServerConfigs(ctx context.Context) (bool, error) {
	return r.ServerConfigService.DeleteAllServerConfigs(ctx)
}

// AllServerConfigs is the resolver for the allServerConfigs field.
func (r *queryResolver) AllServerConfigs(ctx context.Context) ([]*model.ServerConfig, error) {
	return r.ServerConfigService.GetAllConfigs(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
