// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Dealer struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Location string     `json:"location"`
	Vehicles []*Vehicle `json:"vehicles,omitempty"`
}

type DealerCondition struct {
	Key      DealerFilterKey `json:"key"`
	Value    string          `json:"value"`
	Operator Operator        `json:"operator"`
}

type DealerFilter struct {
	Conditions      []*DealerCondition `json:"conditions,omitempty"`
	LogicalOperator *LogicalOperator   `json:"logicalOperator,omitempty"`
}

type PerformanceRequirements struct {
	APIUsageFrequency APIUsageFrequency `json:"apiUsageFrequency"`
	RequestVolume     RequestVolume     `json:"requestVolume"`
	HighAvailability  bool              `json:"highAvailability"`
	BatchLoad         bool              `json:"batchLoad"`
}

type PerformanceRequirementsInput struct {
	APIUsageFrequency APIUsageFrequency `json:"apiUsageFrequency"`
	RequestVolume     RequestVolume     `json:"requestVolume"`
	HighAvailability  bool              `json:"highAvailability"`
	BatchLoad         bool              `json:"batchLoad"`
}

type ResourceConfig struct {
	MaxMemory   string `json:"maxMemory"`
	MinMemory   string `json:"minMemory"`
	MaxCPU      string `json:"maxCPU"`
	MinCPU      string `json:"minCPU"`
	MinReplicas int    `json:"minReplicas"`
}

type ServerConfig struct {
	ID                      string                   `json:"id"`
	ApiserverName           string                   `json:"apiserverName"`
	ContextPath             string                   `json:"contextPath"`
	Features                []Feature                `json:"features"`
	PerformanceRequirements *PerformanceRequirements `json:"performanceRequirements"`
}

type ServerConfigInput struct {
	ApiserverName           string                        `json:"apiserverName"`
	ContextPath             string                        `json:"contextPath"`
	Features                []Feature                     `json:"features"`
	PerformanceRequirements *PerformanceRequirementsInput `json:"performanceRequirements"`
}

type Vehicle struct {
	ID    string `json:"id"`
	Make  string `json:"make"`
	Model string `json:"model"`
	Year  int    `json:"year"`
}

type VehicleCondition struct {
	Key      VehicleFilterKey `json:"key"`
	Value    string           `json:"value"`
	Operator Operator         `json:"operator"`
}

type VehicleFilter struct {
	Conditions      []*VehicleCondition `json:"conditions,omitempty"`
	LogicalOperator *LogicalOperator    `json:"logicalOperator,omitempty"`
}

type APIUsageFrequency string

const (
	APIUsageFrequencyLow    APIUsageFrequency = "LOW"
	APIUsageFrequencyMedium APIUsageFrequency = "MEDIUM"
	APIUsageFrequencyHigh   APIUsageFrequency = "HIGH"
)

var AllAPIUsageFrequency = []APIUsageFrequency{
	APIUsageFrequencyLow,
	APIUsageFrequencyMedium,
	APIUsageFrequencyHigh,
}

func (e APIUsageFrequency) IsValid() bool {
	switch e {
	case APIUsageFrequencyLow, APIUsageFrequencyMedium, APIUsageFrequencyHigh:
		return true
	}
	return false
}

func (e APIUsageFrequency) String() string {
	return string(e)
}

func (e *APIUsageFrequency) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = APIUsageFrequency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApiUsageFrequency", str)
	}
	return nil
}

func (e APIUsageFrequency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DealerFilterKey string

const (
	DealerFilterKeyName     DealerFilterKey = "NAME"
	DealerFilterKeyLocation DealerFilterKey = "LOCATION"
)

var AllDealerFilterKey = []DealerFilterKey{
	DealerFilterKeyName,
	DealerFilterKeyLocation,
}

func (e DealerFilterKey) IsValid() bool {
	switch e {
	case DealerFilterKeyName, DealerFilterKeyLocation:
		return true
	}
	return false
}

func (e DealerFilterKey) String() string {
	return string(e)
}

func (e *DealerFilterKey) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DealerFilterKey(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DealerFilterKey", str)
	}
	return nil
}

func (e DealerFilterKey) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Feature string

const (
	FeatureVehicle   Feature = "VEHICLE"
	FeatureDealer    Feature = "DEALER"
	FeatureUser      Feature = "USER"
	FeatureInventory Feature = "INVENTORY"
)

var AllFeature = []Feature{
	FeatureVehicle,
	FeatureDealer,
	FeatureUser,
	FeatureInventory,
}

func (e Feature) IsValid() bool {
	switch e {
	case FeatureVehicle, FeatureDealer, FeatureUser, FeatureInventory:
		return true
	}
	return false
}

func (e Feature) String() string {
	return string(e)
}

func (e *Feature) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Feature(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Feature", str)
	}
	return nil
}

func (e Feature) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type LogicalOperator string

const (
	LogicalOperatorAnd LogicalOperator = "AND"
	LogicalOperatorOr  LogicalOperator = "OR"
)

var AllLogicalOperator = []LogicalOperator{
	LogicalOperatorAnd,
	LogicalOperatorOr,
}

func (e LogicalOperator) IsValid() bool {
	switch e {
	case LogicalOperatorAnd, LogicalOperatorOr:
		return true
	}
	return false
}

func (e LogicalOperator) String() string {
	return string(e)
}

func (e *LogicalOperator) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogicalOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogicalOperator", str)
	}
	return nil
}

func (e LogicalOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Operator string

const (
	OperatorEqual       Operator = "EQUAL"
	OperatorNotEqual    Operator = "NOT_EQUAL"
	OperatorGreaterThan Operator = "GREATER_THAN"
	OperatorLessThan    Operator = "LESS_THAN"
	OperatorContains    Operator = "CONTAINS"
)

var AllOperator = []Operator{
	OperatorEqual,
	OperatorNotEqual,
	OperatorGreaterThan,
	OperatorLessThan,
	OperatorContains,
}

func (e Operator) IsValid() bool {
	switch e {
	case OperatorEqual, OperatorNotEqual, OperatorGreaterThan, OperatorLessThan, OperatorContains:
		return true
	}
	return false
}

func (e Operator) String() string {
	return string(e)
}

func (e *Operator) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Operator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Operator", str)
	}
	return nil
}

func (e Operator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RequestVolume string

const (
	RequestVolumeSmall  RequestVolume = "SMALL"
	RequestVolumeMedium RequestVolume = "MEDIUM"
	RequestVolumeLarge  RequestVolume = "LARGE"
)

var AllRequestVolume = []RequestVolume{
	RequestVolumeSmall,
	RequestVolumeMedium,
	RequestVolumeLarge,
}

func (e RequestVolume) IsValid() bool {
	switch e {
	case RequestVolumeSmall, RequestVolumeMedium, RequestVolumeLarge:
		return true
	}
	return false
}

func (e RequestVolume) String() string {
	return string(e)
}

func (e *RequestVolume) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RequestVolume(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RequestVolume", str)
	}
	return nil
}

func (e RequestVolume) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type VehicleFilterKey string

const (
	VehicleFilterKeyMake  VehicleFilterKey = "MAKE"
	VehicleFilterKeyModel VehicleFilterKey = "MODEL"
	VehicleFilterKeyYear  VehicleFilterKey = "YEAR"
)

var AllVehicleFilterKey = []VehicleFilterKey{
	VehicleFilterKeyMake,
	VehicleFilterKeyModel,
	VehicleFilterKeyYear,
}

func (e VehicleFilterKey) IsValid() bool {
	switch e {
	case VehicleFilterKeyMake, VehicleFilterKeyModel, VehicleFilterKeyYear:
		return true
	}
	return false
}

func (e VehicleFilterKey) String() string {
	return string(e)
}

func (e *VehicleFilterKey) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VehicleFilterKey(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VehicleFilterKey", str)
	}
	return nil
}

func (e VehicleFilterKey) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
